// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "test.h"

void CubeViewUI::cb_slider_i(Fl_Slider* o, void*) {
  cube->pany(((Fl_Slider*)o)->value());
cube->redraw();
}
void CubeViewUI::cb_slider(Fl_Slider* o, void* v) {
  ((CubeViewUI*)(o->parent()->parent()->user_data()))->cb_slider_i(o,v);
}

Fl_Double_Window* CubeViewUI::CubeUIView() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(1065, 935);
    w = o;
    o->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(40, 105, 230, 480, "VChange");
      o->box(FL_UP_BOX);
      { new Fl_Roller(115, 155, 45, 395, "vRot");
      } // Fl_Roller* o
      { Fl_Slider* o = new Fl_Slider(190, 155, 40, 395, "slider:yPan");
        o->type(4);
        o->box(FL_UP_BOX);
        o->callback((Fl_Callback*)cb_slider);
        o->align(Fl_Align(FL_ALIGN_CENTER));
      } // Fl_Slider* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(310, 605, 675, 145, "HChange");
      o->box(FL_UP_BOX);
      o->align(Fl_Align(135));
      { Fl_Roller* o = new Fl_Roller(420, 700, 475, 25, "hRot");
        o->type(1);
      } // Fl_Roller* o
      { Fl_Slider* o = new Fl_Slider(420, 630, 475, 40, "slider:xPan");
        o->type(5);
      } // Fl_Slider* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(250, 50, 765, 525, "MainView");
      o->align(Fl_Align(65));
      { Fl_Box* o = new Fl_Box(285, 134, 710, 441, "cFrame");
        o->box(FL_DOWN_BOX);
      } // Fl_Box* o
      { cube = new CubeView(330, 180, 620, 385, "CubeView");
        cube->box(FL_NO_BOX);
        cube->color(FL_BACKGROUND_COLOR);
        cube->selection_color(FL_BACKGROUND_COLOR);
        cube->labeltype(FL_NORMAL_LABEL);
        cube->labelfont(0);
        cube->labelsize(14);
        cube->labelcolor(FL_FOREGROUND_COLOR);
        cube->align(Fl_Align(FL_ALIGN_CENTER));
        cube->when(FL_WHEN_RELEASE);
      } // CubeView* cube
      o->end();
    } // Fl_Group* o
    { Fl_Value_Slider* o = new Fl_Value_Slider(285, 79, 700, 18, "Zoom");
      o->type(5);
      o->maximum(10);
      o->value(5);
      o->slider_size(1);
      o->textsize(14);
      o->align(Fl_Align(418));
    } // Fl_Value_Slider* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}

void CubeViewUI::show(int argc, char **argv) {
    cube->draw();
    return;
}


