// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef test_h
#define test_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Roller.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Box.H>
#include "CubeView.h"
#include <FL/Fl_Value_Slider.H>

class CubeViewUI {
public:
  Fl_Double_Window* CubeUIView();
private:
  inline void cb_slider_i(Fl_Slider*, void*);
  static void cb_slider(Fl_Slider*, void*);
public:
  CubeView *cube;
  void show(int argc, char **argv);
};
#endif
