// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "delaunayTriangleTest.h"
#include "TestModel.h"

using namespace CrystalMesh;
using namespace UI;

DelaunayTestView *TestView=(DelaunayTestView *)0;

int main(int argc, char **argv) {
    
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(600, 600, "MainWindow");
    w = o;
    { TestView = new DelaunayTestView(100, 100, 400, 400, "glDisplay");
      TestView->box(FL_DOWN_BOX);
      TestView->color(FL_BACKGROUND_COLOR);
      TestView->selection_color(FL_BACKGROUND_COLOR);
      TestView->labeltype(FL_NORMAL_LABEL);
      TestView->labelfont(0);
      TestView->labelsize(14);
      TestView->labelcolor(FL_FOREGROUND_COLOR);
      TestView->align(Fl_Align(FL_ALIGN_CENTER));
      TestView->when(FL_WHEN_RELEASE);
    } // DelaunayTestView* TestView
    { Fl_Roller* o = new Fl_Roller(78, 513, 446, 24);
      o->type(1);
      o->maximum(360);
      o->step(1);
      o->callback((Fl_Callback*)hRotate);
    } // Fl_Roller* o
    { Fl_Slider* o = new Fl_Slider(210, 546, 217, 24, "slider:");
      o->type(1);
      o->minimum(-1);
      o->step(0.1);
      o->callback((Fl_Callback*)xShift);
    } // Fl_Slider* o
    o->end();
  } // Fl_Double_Window* o
  
  triangleTest_launch();
  w->show(argc, argv);
  
  return Fl::run();
  triangleTest_tearDown();
}

/**
   //horizontal rotation
*/
void hRotate(Fl_Roller* widget,void*) {
  double angle = widget->value();
  //    cube->h_angle(angle);
  //    cube->redraw();
      return;
}

/**
   shift in x dir
*/
void xShift(Fl_Roller* widget,void*) {
  //shift in x dir
  //    cube->panx(widget->value());
  //    cube->redraw();
}
