// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "fluid02.h"
#include <iostream>
#include <string>

Fl_Output *output=(Fl_Output *)0;

Fl_Input *textInput=(Fl_Input *)0;

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(240, 240, "Hauptfenster");
    w = o;
    { Fl_Button* o = new Fl_Button(100, 200, 70, 20, "Knopf");
      o->callback((Fl_Callback*)Button_CB);
    } // Fl_Button* o
    { output = new Fl_Output(65, 133, 156, 57, "Output");
    } // Fl_Output* output
    { textInput = new Fl_Input(88, 81, 134, 40, "Text input");
    } // Fl_Input* textInput
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}

void Button_CB(Fl_Widget*,void*) {
  //code on button
  char const str[] = "Hello fluid";
  std::string fromInput(textInput->value());
  //std::cout << str<< std::endl;
  //output->value(fromInput->c_str());
  output->value(fromInput.c_str());
}
