// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "fluid01.h"
#include <iostream>

void Button_CB(Fl_Widget*,void*) {
  //code on button
  char const str[] = "Hello fluid";
  std::cout << str<< std::endl;
  output->value(str);
}

Fl_Output *output=(Fl_Output *)0;

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(240, 240, "Hauptfenster");
    w = o;
    { Fl_Button* o = new Fl_Button(80, 95, 70, 20, "Knopf");
      o->callback((Fl_Callback*)Button_CB);
    } // Fl_Button* o
    { output = new Fl_Output(65, 28, 156, 57, "Output");
    } // Fl_Output* output
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
