// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef fluid03_h
#define fluid03_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Output.H>
extern Fl_Output *output;
#include <FL/Fl_Input.H>
extern Fl_Input *textInput;
void Button_CB(Fl_Widget*,void*);
Fl_Window* NewWindow();
void Button_PopWin(Fl_Widget* ,void*);
#endif
