// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef fluid01_h
#define fluid01_h
#include <FL/Fl.H>
void Button_CB(Fl_Widget*,void*);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Output.H>
extern Fl_Output *output;
#endif
