// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef fluid04_h
#define fluid04_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "CubeView.h"
extern CubeView *cube;
#include <FL/Fl_Roller.H>
#include <FL/Fl_Slider.H>
void hRotate(Fl_Roller* widget,void*);
void xShift(Fl_Roller* widget,void*);
#endif
